import React, { useEffect, useRef } from 'react';
const hash=n=>{const x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)};
const hex=v=>{const s=String(v||'#000000').replace('#','').padEnd(6,'0');return[parseInt(s.slice(0,2),16)||0,parseInt(s.slice(2,4),16)||0,parseInt(s.slice(4,6),16)||0]};
const rgba=(c,a=1)=>{const[r,g,b]=hex(c);return`rgba(${r},${g},${b},${a})`};
export default function ProceduralBackground({variant='waves',width,height,color1='#7c3aed',color2='#06b6d4',color3='#ec4899',backgroundColor='#050816',speed=.5,intensity=1,opacity=1,scale=1,noise=.35,time}){
 const ref=useRef(null),raf=useRef(null),drawRef=useRef(null),timeRef=useRef(time);timeRef.current=time;
 useEffect(()=>{
  const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');let dpr=1;
  const resize=()=>{const r=canvas.getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.round((r.width||width||1)*dpr));canvas.height=Math.max(1,Math.round((r.height||height||1)*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)};resize();const ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;ro?.observe(canvas);
  const draw=(ms)=>{const t=timeRef.current==null?ms/1000:Number(timeRef.current||0),w=canvas.clientWidth||width||1,h=canvas.clientHeight||height||1;ctx.clearRect(0,0,w,h);ctx.globalAlpha=opacity;ctx.fillStyle=backgroundColor;ctx.fillRect(0,0,w,h);const c1=rgba(color1,Math.min(1,intensity)),c2=rgba(color2,Math.min(1,intensity)),c3=rgba(color3,Math.min(1,intensity)),v=String(variant).toLowerCase(),s=Math.max(.15,Number(scale)||1),sp=Number(speed)||0;
   if(['aurora','soft-aurora','aurora-beam','aurora-blur','silk','waves','sliced-waves','mosaic-waves','chroma-waves','line-waves','swirl-blend'].includes(v)){const bands=v.includes('mosaic')?14:9;for(let i=0;i<bands;i++){const y=h*(i+1)/(bands+1);ctx.beginPath();for(let x=0;x<=w;x+=8){const yy=y+Math.sin(x/(80*s)+t*(.35+sp*.8)+i)*h*.055+Math.sin(x/(27*s)-t*.25)*h*.018;x===0?ctx.moveTo(x,yy):ctx.lineTo(x,yy)}ctx.strokeStyle=[c1,c2,c3][i%3];ctx.lineWidth=Math.max(2,h*.025);ctx.globalAlpha=opacity*.22;ctx.shadowBlur=28;ctx.shadowColor=ctx.strokeStyle;ctx.stroke()}}
   else if(v.includes('grid')||['scanner','radar'].includes(v)){const gap=Math.max(18,48/s);ctx.lineWidth=1;ctx.globalAlpha=opacity*.32;ctx.strokeStyle=c2;for(let x=-h;x<w+h;x+=gap){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+h,h);ctx.stroke()}for(let y=0;y<h;y+=gap){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(v.includes('scan')||v==='scanner'){const y=(t*80*sp)%h;ctx.fillStyle=c1;ctx.globalAlpha=opacity*.55;ctx.fillRect(0,y,w,2)}if(v==='radar'){ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*.32,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.lineTo(w/2+Math.cos(t*sp)*w,h/2+Math.sin(t*sp)*w);ctx.stroke()}}
   else if(v.includes('particle')||['dot-field','blinking-dots','pixel-snow','pixel-blast','star-swipe','rotating-stars','glitter-warp'].includes(v)){const count=Math.round(70+100*noise);for(let i=0;i<count;i++){const x=(hash(i*3.1)*w+Math.sin(t*sp*.2+i)*12)%w,y=(hash(i*7.7)*h+(v.includes('rising')?-t*40*sp:t*12*sp))%h,r=1+hash(i*4.3)*3;ctx.fillStyle=[c1,c2,c3][i%3];ctx.globalAlpha=opacity*(.25+hash(i*2.2)*.65);ctx.fillRect((x+w)%w,(y+h)%h,r,r)}}
   else if(['acid-squares','blinking-squares','glass-tiles','glass-flow','liquid-bars','gradient-bars','shadow-bars'].includes(v)){const size=Math.max(24,Math.min(100,w/10));for(let y=-size;y<h+size;y+=size)for(let x=-size;x<w+size;x+=size){const q=Math.sin(t*sp*2+x*.01+y*.02);ctx.fillStyle=[c1,c2,c3][Math.abs(Math.round(x/size+y/size))%3];ctx.globalAlpha=opacity*(.08+.12*(q+1));ctx.fillRect(x+q*8,y+Math.sin(t+x*.01)*8,size-3,size-3)}}
   else if(['faulty-terminal','letter-glitch','ascii-tiles','ascii-waves','crt-warp','halftone-wave','neon-reveal'].includes(v)){ctx.font='12px monospace';ctx.fillStyle=c2;ctx.globalAlpha=opacity*.5;const chars='01<>[]{}/*#$%@';for(let y=14;y<h;y+=16)for(let x=0;x<w;x+=10)if(hash(x+y+Math.floor(t*sp*8))>.72)ctx.fillText(chars[Math.floor(hash(x*2+y)*chars.length)],x,y);if(v==='crt-warp'){ctx.globalAlpha=opacity*.08;ctx.fillStyle='#fff';for(let y=0;y<h;y+=4)ctx.fillRect(0,y,w,1)}}
   else if(['beams','light-rays','side-rays','light-pillar','lightning','falling-rays','rising-lines','floating-lines'].includes(v)){for(let i=0;i<10;i++){const x=(i+1)*w/11+Math.sin(t*sp+i)*w*.08;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+w*.18,h);ctx.strokeStyle=[c1,c2,c3][i%3];ctx.globalAlpha=opacity*.22;ctx.lineWidth=8+hash(i)*20;ctx.shadowBlur=35;ctx.shadowColor=ctx.strokeStyle;ctx.stroke()}}
   else if(['liquid-chrome','liquid-ether','ferrofluid','molten-metal','metallic-swirl','watercolor','plasma','plasma-wave','color-bends','color-loops','dither','iridescence','prism','prismatic-burst','vortex','warp-twister','dark-veil','black-hole','orb','galaxy'].some(k=>v.includes(k))){const g=ctx.createRadialGradient(w*.5+Math.cos(t*sp)*w*.18,h*.5+Math.sin(t*sp*.7)*h*.18,0,w*.5,h*.5,Math.max(w,h)*.72);g.addColorStop(0,c1);g.addColorStop(.42,c2);g.addColorStop(1,c3);ctx.globalAlpha=opacity*.75;ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(w*.5,h*.5,Math.min(w,h)*(.08+i*.08)+Math.sin(t*sp+i)*10,0,Math.PI*2);ctx.strokeStyle=[c1,c2,c3][i%3];ctx.globalAlpha=opacity*.12;ctx.lineWidth=3;ctx.stroke()}}
   else{const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,c1);g.addColorStop(.5,c2);g.addColorStop(1,c3);ctx.fillStyle=g;ctx.globalAlpha=opacity*.75;ctx.fillRect(0,0,w,h)}ctx.globalAlpha=1};
  drawRef.current=draw;if(time==null)raf.current=requestAnimationFrame(function loop(ms){draw(ms);raf.current=requestAnimationFrame(loop)});else draw(0);
  return()=>{if(raf.current)cancelAnimationFrame(raf.current);ro?.disconnect();drawRef.current=null};
 },[variant,width,height,color1,color2,color3,backgroundColor,speed,intensity,opacity,scale,noise]);
 useEffect(()=>{timeRef.current=time;if(time!=null)drawRef.current?.(0)},[time]);
 return <canvas ref={ref} style={{position:'absolute',inset:0,width:'100%',height:'100%',display:'block'}}/>;
}
